name: Jekyll site CI

on:
  push:
    branches: [ jekyll-source ]

jobs:
  build:

    runs-on: ubuntu-latest
    # container:
    #   image: jekyll/builder:latest
    #   env:
    #     JEKYLL_ENV: production
    #   volumes:
    #     - ${{ github.workspace }}/source:/srv/jekyll
    #     - ${{ github.workspace }}/source/_site:/srv/jekyll/_site
    #   options: --cpus 1

    steps:
    - name: Checkout jekyll-source
      uses: actions/checkout@v2
      with:
        ref: 'jekyll-source'
        path: 'source'

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}/source:/srv/jekyll -v ${{ github.workspace }}/source/_site:/srv/jekyll/_site \
         -e JEKYLL_ENV=production \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

    - name: Cloning master branch
      uses: actions/checkout@v2
      with:
        ref: 'master'
        path: 'master'

    - name: Copying _site content to master branch repo
      run: cp -R ${{ github.workspace }}/source/_site/* ${{ github.workspace }}/master

    - name: Commit files
      run: |
        cd ${{ github.workspace }}/master
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -m "New changes" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: ${{ github.workspace }}/master
        branch: 'master'
        github_token: ${{ secrets.GITHUB_TOKEN }}